# Proyecto final 
## Joaquín Antonio Ramírez Hernández

Ejercicio 2

Aquí se cargan las paqueterías a utilizar

In [4]:
from scipy import stats
import numpy as np
import pandas as pd 
import math
import matplotlib.pyplot as plt
from random import seed

In [5]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer

Aquí se definen las operaciones de la tabla de verdad. La operación $x_{1}\&x_{2}$ se define como $x_{1}yx_{2}$ en el código, mientras que la operación $x_{1}\$x_{2}$ se define como $x_{1}px_{2}$ en el código. 

Por otra parte, se toma un arreglo de (4,2) para describir los valores que toman $x_{1}$ y $x_{2}$ en la tabla de verdad, por lo cual, las operaciones \$,\& son funciones que toman arreglos de (4,2) y regresan un arreglo de (4,1). 

Por último, dado que A toma valores distintos de 1 y 0 en algunos casos, estos se redondean para definir las operaciones binarias del problema en cuestión.

In [7]:
AyB=np.array([(1.001,0),(0,1),(0.001,0), (1,1)]).round()
x1ux2=np.array([(0,0),(1,0),(0,1),(1,1)])
x1yx2 = np.array([1,1,1,0])
x1px2 = np.array([0,0,0,1])

Se propone para las dos operaciones dos redes neuronales que contienen cada una 2 entradas, 4 neuronas y 1 salida. 

Las primeras 4 neuronas se activan por la función 'relu', mientras que la de salida se activa por la función 'sigmoidal'. Ésta última la definimos así, ya que, una tabla de verdad (en esencia) es una clasificación binaria.

Para el entrenamiento de las redes neuronales se propone como optimizador el método 'adam', como función de perdida 'mean_squared_error' y como métrica 'binary_accuracy', ésta última tomada así porque se busca una clasificación binaria; sin embargo, para el entrenamiento de la primera red neuronal se hacen 700 iteraciones mientras que en la segunda se hacen 500 iteraciones. 

In [703]:
model1 = Sequential()
model1.add(Dense(units=4, activation='relu',input_dim=2))
model1.add(Dense(units=1, activation='sigmoid'))
model1.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])
model1.fit(x1ux2,x1yx2,epochs=700)

Epoch 1/700
1/1 [==============================] - 0s 288ms/step - loss: 0.2551 - binary_accuracy: 0.5000
Epoch 2/700
1/1 [==============================] - 0s 4ms/step - loss: 0.2549 - binary_accuracy: 0.7500
Epoch 3/700
1/1 [==============================] - 0s 2ms/step - loss: 0.2546 - binary_accuracy: 0.7500
Epoch 4/700
1/1 [==============================] - 0s 6ms/step - loss: 0.2543 - binary_accuracy: 0.7500
Epoch 5/700
1/1 [==============================] - 0s 2ms/step - loss: 0.2541 - binary_accuracy: 0.7500
Epoch 6/700
1/1 [==============================] - 0s 7ms/step - loss: 0.2538 - binary_accuracy: 0.7500
Epoch 7/700
1/1 [==============================] - 0s 3ms/step - loss: 0.2535 - binary_accuracy: 0.7500
Epoch 8/700
1/1 [==============================] - 0s 5ms/step - loss: 0.2533 - binary_accuracy: 0.7500
Epoch 9/700
1/1 [==============================] - 0s 3ms/step - loss: 0.2530 - binary_accuracy: 0.7500
Epoch 10/700
1/1 [==============================] - 0s 6ms/ste

Como se puede observar, se obtiene una exactitud del 100\% para la operación $\&$

In [704]:
_,accuracy=model1.evaluate(x1ux2,x1yx2)
print('Accuracy:%.2f'% (accuracy*100))

1/1 [==============================] - 0s 130ms/step - loss: 0.0709 - binary_accuracy: 1.0000
Accuracy:100.00


In [705]:
model1.predict(x1ux2).round()

array([[1.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [706]:
model2 = Sequential()
model2.add(Dense(units=4, activation='relu',input_dim=2))
model2.add(Dense(units=1, activation='sigmoid'))
model2.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])
model2.fit(x1ux2,x1px2,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 295ms/step - loss: 0.2741 - binary_accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2735 - binary_accuracy: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2729 - binary_accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2723 - binary_accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2717 - binary_accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2711 - binary_accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2705 - binary_accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2699 - binary_accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 0.2693 - binary_accuracy: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 3ms/ste

Y también se obtiene una exactitud del 100\% para la operación \$

In [707]:
_,accuracy=model2.evaluate(x1ux2,x1px2)
print('Accuracy:%.2f'% (accuracy*100))

1/1 [==============================] - 0s 125ms/step - loss: 0.1125 - binary_accuracy: 1.0000
Accuracy:100.00


In [711]:
model2.predict(x1ux2).round()

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

Finalmente, se obtiene $A\&B$ utilizando la red neuronal. Haciendo la operación \& a mano y tomando en cuenta las convenciones anteriores se obtiene que 
$$A\&B=\begin{array}{c}
1\\
1\\
1\\
0
\end{array}$$

lo cual, coincide con lo obtenido por la red neuronal.

In [713]:
D=model1.predict(AyB).round()
D

array([[1.],
       [1.],
       [1.],
       [0.]], dtype=float32)

Luego, se obtiene $(A\&B)\$C$,lo cual, haciendo la operación a mano se obtiene que
$$(A\&B)\$C=\begin{array}{c}
0\\
1\\
1\\
0
\end{array}$$

lo cual, coincide con lo obtenido por la red neuronal

In [715]:
DpC=np.array([(1,0),(1,1),(1,1),(0,0)])
DpC

array([[1, 0],
       [1, 1],
       [1, 1],
       [0, 0]])

In [717]:
model2.predict(DpC).round()

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)